apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-todo
  template:
    metadata:
      labels:
        app: mini-todo
    spec:
      containers:
      - name: 
        image: ayeshadocker25/todoreact:03
        ports:
        - containerPort: 80